// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhqdi6WbZJqkqz7IYn5B_-ElMMiPl9E4',
    appId: '1:234276530159:android:924a955ba82b0de040781a',
    messagingSenderId: '234276530159',
    projectId: 'zero-eb36e',
    storageBucket: 'zero-eb36e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZoNnyaActKctj1Q-nV-Zd0vVw2eYGW0',
    appId: '1:234276530159:ios:95ad0bcbbdebbdca40781a',
    messagingSenderId: '234276530159',
    projectId: 'zero-eb36e',
    storageBucket: 'zero-eb36e.appspot.com',
    androidClientId: '234276530159-8tf9nka5am58d8gt98imqnoa423ef3jr.apps.googleusercontent.com',
    iosClientId: '234276530159-7r6m7c3q6bbhl84potrb212ho2ulnt8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.zero',
  );
}
